
# GENERAL
DATA_RAW = './data_raw'
DATA_TEMP_AUDIO = './data_temp_audio'
DATA_TRANSCRIBED_TEXT = './data_transcribed_text'
DATA_PRE_PROCESSED_ONE = './data_pre_processed'

#WHISPER
WHISPER_LOAD_MODEL = 'base'

# OPENAI
OPENAI_API_KEY = ''
OPENAI_MODEL = 'gpt-4'
OPENAI_MAX_TOKENS = 4096
OPENAI_RESPONSE_TOKENS = 500

# YOUTUBE
YOUTUBE_API_KEY = ''

# SENTIMENT SCORES
SENTIMENT_POSITIVE_SCORE = 0.05
SENTIMENT_NEGATIVE_SCORE = -0.05

# PHRASE_EXTRACTION
NUMBER_OF_PHRASES = 3

# KEYWORD EXTRACTION
KEYWORD_EXTRACTION_MODEL = 'all-mpnet-base-v2'
NUMBER_OF_KEYWORDS = 5

#MISC
LENGTH_OF_OUTPUT_SUMMARIZATION = 350